Update cicd.yaml

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -178,23 +178,17 @@ jobs:
 
       - name: Run SA and Secret Script
         id: run_sa_script
-        run: |
-          chmod +x ./scripts/setup_sa.sh
-          ./scripts/setup_sa.sh
         env:
-          KUBECONFIG: $HOME/.kube/config       
-
-      - name: Save K8s token to file
-        if: success()
+          GH_TOKEN: ${{ secrets.GH_PAT_SECRET_ADMIN }}
         run: |
-          printf '%s' "$K8S_TOKEN" > k8s_token.txt
+          K8S_TOKEN=$(./scripts/setup-sa.sh)
+          
+          if [ -z "$K8S_TOKEN" ]; then
+            echo "Failed to capture token"
+            exit 1
+          fi
 
-      - name: Upload K8s token artifact
-        if: success()
-        uses: actions/upload-artifact@v4
-        with:
-          name: k8s-token
-          path: k8s_token.txt
+          gh secret set K8S_CLUSTER_TOKEN --body "$K8S_TOKEN" --repo ${{ github.repository }}
 
   # ============================================================
   # Job 3: K8s Configuration (Deployments, Services, Helm)
@@ -211,17 +205,6 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 2
-
-      - name: Download K8s token artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: k8s-token
-
-      - name: Set TF_VAR_k8s_token from artifact
-        run: |
-          if [ -f k8s_token.txt ]; then
-            echo "TF_VAR_k8s_token=$(cat k8s_token.txt)" >> $GITHUB_ENV
-          fi
 
       - name: Check for changes in k8s
         id: filter
@@ -276,7 +259,7 @@ jobs:
         working-directory: k8s
         env:
           TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
-          TF_VAR_k8s_token: ${{ needs.setup-sa-secrets.outputs.k8s_token }}
+          TF_VAR_k8s_token: ${{ secrets.K8S_CLUSTER_TOKEN }}
 
       - name: Terraform Apply
         if: steps.filter.outputs.run_apply == 'true'
@@ -284,4 +267,5 @@ jobs:
         working-directory: k8s
         env:
           TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
-          TF_VAR_k8s_token: ${{ needs.setup-sa-secrets.outputs.k8s_token }}
+          TF_VAR_k8s_token: ${{ secrets.K8S_CLUSTER_TOKEN }}
+          
